#pragma once

#include "includes.h"
#include "extern.h"
#include "vga.h"
#include "paging.h"
#include "buddy_alloc.h"
#include "slab_alloc.h"
#include "set_gdt.h"
#include "set_idt.h"
#include "timer.h"
#include "keyboard.h"
#include "E820.h"
#include "vfs.h"
#include "acpi.h"
#include "apic.h"
#include "utility.h"
#include "pci.h"
#include "ahci_driver.h"
#include "mbr.h"
#include "ext2_sb_ops.h"
#include "rtc.h"
#include "blocks_buffer.h"
#include "ext2_ino_ops.h"
#include "ext2_file_ops.h"

void kmain();