#pragma once
#include "includes.h"

#define NUM_CACHE 2
#define VGA_BUFFER ((volatile char*)(uint32_t) KERNEL_VIRTUAL + 0xB8000)
#define PAGE_SIZE 4096
#define KERNEL_VIRTUAL 0x80000000
#define KERNEL_BASE 0x100000
#define TABLE_SIZE PAGE_SIZE * 1024
#define HIGHER_HALF_IDX 512
#define E820_SIGNATURE 0x534D4150
#define E820_ADDRESS KERNEL_VIRTUAL + 0x500
#define MAX_ORDER 32
#define SLAB_GARBAGE_BYTE 0xAC
#define PAGE_SIZE_LOG2 12
#define GREY_COLOR 0x07
#define RED_COLOR 0x04

// GDT Definitions
#define GDT_LIMIT 0xFFFFF
#define GDT_BASE 0x0
#define PRESENT 1
#define NOT_PRESENT 0
#define TYPE_DATA_NON_EXECUTABLE 0
#define PRIVILEGE_KERNEL 0
#define PRIVILEGE_USER 3
#define DESCRIPTOR_TYPE_CODE_DATA 1
#define DESCRIPTOR_TYPE_SYSTEM 0
#define TYPE_CODE_EXECUTABLE 1
#define TYPE_DATA_READABLE_WRITABLE 1
#define TYPE_DATA_EXPAND_DOWN 0
#define TYPE_CODE_CONFORMING 0
#define TYPE_ACCESSSED 0
#define GRANULARITY_4KB 1
#define GRANULARITY_BYTE 0
#define DEFAULT_BIG_32BIT 1
#define DEFAULT_BIG_16BIT 0
#define LONG_MODE_64BIT 1
#define LONG_MODE_32BIT 0
#define RESERVED 0
// End GDT Definitions

// IDT Definitions
#define IDT_SIZE 256
#define GDT_CODE_SEGMENT 0x08
#define IDT_TYPE_INTERRUPT_GATE 0xE
#define IDT_TYPE_TRAP_GATE 0xF