#pragma once
#include "includes.h"

#define LEFT_SHIFT_MAKE_SCANCODE 0x2A
#define LEFT_SHIFT_BREAK_SCANCODE 0xAA
#define RIGHT_SHIFT_MAKE_SCANCODE 0x36
#define RIGHT_SHIFT_BREAK_SCANCODE 0xB6

#define CONSOLE_BUFFER_SIZE 512
#define KEYBOARD_MS_BACK 10
