#pragma once
#include "includes.h"

#define GDT_LIMIT 0xFFFFF
#define GDT_BASE 0x0
#define PRESENT 1
#define NOT_PRESENT 0
#define TYPE_DATA_NON_EXECUTABLE 0
#define PRIVILEGE_KERNEL 0
#define PRIVILEGE_USER 3
#define DESCRIPTOR_TYPE_CODE_DATA 1
#define DESCRIPTOR_TYPE_SYSTEM 0
#define TYPE_CODE_EXECUTABLE 1
#define TYPE_DATA_READABLE_WRITABLE 1
#define TYPE_DATA_EXPAND_DOWN 0
#define TYPE_CODE_CONFORMING 0
#define TYPE_ACCESSSED 0
#define GRANULARITY_4KB 1
#define GRANULARITY_BYTE 0
#define DEFAULT_BIG_32BIT 1
#define DEFAULT_BIG_16BIT 0
#define LONG_MODE_64BIT 1
#define LONG_MODE_32BIT 0
#define RESERVED 0
